.TH Gource 1
.SH NAME
Gource - a software version control visualization
.SH SYNOPSIS
\fIgource\fR
[options] [path]
.SH DESCRIPTION
\fIgource\fR is an OpenGL-based 3D visualisation tool for source control repositories.

The repository is displayed as a tree where the root of the repository is the centre, directories are branches and files are leaves. Contributors to the source code appear and disappear as they contribute to specific files and directories.
.SH REQUIREMENTS
\fIgource\fR
requires a OpenGL capable video card to run.
.SH OPTIONS
.TP 8
\fB\-h, \-\-help\fR
Help ('\fB-H\fR' for extended help).
.TP
\fB\-WIDTHxHEIGHT, \-\-viewport WIDTHxHEIGHT\fR
Set the viewport size. If \-f is also supplied, will attempt to set the video mode to this also. Add ! to make the window non-resizable.
.TP
\fB\-f\fR
Fullscreen.
.TP
\fB\-\-screen SCREEN\fR
Set the number of the screen to display on.
.TP
\fB\-\-window\-position XxY\fR
Initial window position on your desktop which may be made up of multiple monitors.

This will override the screen setting so don't specify both.
.TP
\fB\-\-frameless\fR
Frameless window.
.TP
\fB\-\-transparent\fR
Make the background transparent. Only really useful for screenshots.
.TP
\fB\-\-start\-date "YYYY\-MM\-DD hh:mm:ss +tz"\fR
Start with the first entry after the supplied date and optional time.

If a time zone offset isn't specified the local time zone is used.

Example accepted formats:

    "2012-06-30"
    "2012-06-30 12:00"
    "2012-06-30 12:00:00 +12"
.TP
\fB\-\-stop\-date "YYYY\-MM\-DD hh:mm:ss +tz"\fR
Stop at the last entry prior to the supplied date and optional time.

Uses the same format as \-\-start\-date.
.TP
\fB\-p, \-\-start\-position POSITION\fR
Begin at some position in the log (between 0.0 and 1.0 or 'random').
.TP
\fB\-\-stop\-position  POSITION\fR
Stop (exit) at some position in the log (does not work with STDIN).
.TP
\fB\-t, \-\-stop\-at\-time SECONDS\fR
Stop (exit) after a specified number of seconds.
.TP
\fB\-\-stop\-at\-end\fR
Stop (exit) at the end of the log / stream.
.TP
\fB\-\-loop\fR
Loop back to the start of the log when the end is reached.
.TP
\fB\-\-loop\-delay\-seconds SECONDS\fR
Seconds to delay before looping.
.TP
\fB\-a, \-\-auto\-skip\-seconds SECONDS\fR
Automatically skip to next entry if nothing happens for a specified number of seconds.
.TP
\fB\-s, \-\-seconds\-per\-day SECONDS\fR
Speed of simulation in seconds per day.
.TP
\fB\-\-realtime\fR
Realtime playback speed.
.TP
\fB\-\-no\-time\-travel\fR
Use the time of the last commit if the time of a commit is in the past.
.TP
\fB\-c, \-\-time\-scale SCALE\fR
Change simulation time scale.
.TP
\fB\-i, \-\-file\-idle\-time SECONDS\fR
Time in seconds files remain idle before they are removed or 0 for no limit.
.TP
\fB\-e, \-\-elasticity FLOAT\fR
Elasticity of nodes.
.TP
\fB\-b, \-\-background-colour FFFFFF\fR
Background colour in hex.
.TP
\fB\-\-background\-image IMAGE\fR
Set a background image.
.TP
\fB\-\-title TITLE\fR
Set a title
.TP
\fB\-\-font\-file FILE\fR
Specify the font. Should work with most font file formats supported by FreeType, such as TTF and OTF, among others.
.TP
\fB\-\-font\-scale SCALE\fR
Scale the size of all fonts.
.TP
\fB\-\-font\-size SIZE\fR
Font size used by the date and title.
.TP
\fB\-\-file\-font\-size SIZE\fR
Font size of filenames.
.TP
\fB\-\-dir\-font\-size SIZE\fR
Font size of directory names.
.TP
\fB\-\-user\-font\-size SIZE\fR
Font size of user names.
.TP
\fB\-\-font\-colour FFFFFF\fR
Font colour used by the date and title in hex.
.TP
\fB\-\-key\fR
Show file extension key.
.TP
\fB\-\-logo IMAGE\fR
Logo to display in the foreground.
.TP
\fB\-\-logo\-offset XxY\fR
Offset position of the logo.
.TP
\fB\-\-date\-format FORMAT\fR
Specify display date string (strftime format).
.TP
\fB\-\-log\-command VCS\fR
Show the log command used by gource (git,svn,hg,bzr,cvs2cl).
.TP
\fB\-\-log\-format VCS\fR
Specify format of the log being read (git,svn,hg,bzr,cvs2cl,custom). Required when reading from STDIN.
.TP
\fB\-\-git\-branch\fR
Get the git log of a branch other than the current one.
.TP
\fB\-\-follow\-user USER\fR
Have the camera automatically follow a particular user.
.TP
\fB\-\-highlight\-dirs\fR
Highlight the names of all directories.
.TP
\fB\-\-highlight\-user USER\fR
Highlight the names of a particular user.
.TP
\fB\-\-highlight\-users\fR
Highlight the names of all users.
.TP
\fB\-\-highlight\-colour FFFFFF\fR
Font colour for highlighted users in hex.
.TP
\fB\-\-selection\-colour FFFFFF\fR
Font colour for selected users and files.
.TP
\fB\-\-filename\-colour FFFFFF\fR
Font colour for filenames.
.TP
\fB\-\-dir\-colour FFFFFF\fR
Font colour for directories.
.TP
\fB\-\-dir\-name\-depth DEPTH\fR
Draw names of directories down to a specific depth in the tree.
.TP
\fB\-\-dir\-name\-position FLOAT
Position along edge of the directory name (between 0.1 and 1.0, default is 0.5).
.TP
\fB\-\-filename\-time SECONDS\fR
Duration to keep filenames on screen (>= 2.0).
.TP
\fB\-\-file\-extensions\fR
Show filename extensions only.
.TP
\fB\-\-file\-extension\-fallback\fR
Use filename as extension if the extension is missing or empty.
.TP
\fB\-\-file\-filter REGEX\fR
Filter out file paths matching the specified regular expression.
.TP
\fB\-\-file\-show\-filter REGEX\fR
Show only file paths matching the specified regular expression.
.TP
\fB\-\-user\-filter REGEX\fR
Filter usernames matching the specified regular expression.
.TP
\fB\-\-user\-show\-filter REGEX\fR
Show only usernames matching the specified regular expression.
.TP
\fB\-\-user\-image\-dir DIRECTORY\fR
Directory containing .jpg or .png images of users (eg "Full Name.png") to use as avatars.
.TP
\fB\-\-default\-user\-image IMAGE\fR
Path of .jpg to use as the default user image.
.TP
\fB\-\-colour\-images\fR
Colourize user images.
.TP
\fB\-\-crop AXIS\fR
Crop view on an axis (vertical,horizontal).
.TP
\fB\-\-padding FLOAT\fR
Camera view padding.
.TP
\fB\-\-multi\-sampling\fR
Enable multi-sampling.
.TP
\fB\-\-no\-vsync\fR
Disable vsync.
.TP
\fB\-\-bloom\-multiplier FLOAT\fR
Adjust the amount of bloom.
.TP
\fB\-\-bloom\-intensity FLOAT\fR
Adjust the intensity of the bloom.
.TP
\fB\-\-max\-files NUMBER\fR
Set the maximum number of files or 0 for no limit. Excess files will be discarded.
.TP
\fB\-\-max\-file\-lag SECONDS\fR
Max time files of a commit can take to appear. Use \-1 for no limit.
.TP
\fB\-\-max\-user\-speed UNITS\fR
Max speed users can travel per second.
.TP
\fB\-\-user\-friction SECONDS\fR
Time users take to come to a halt.
.TP
\fB\-\-user\-scale SCALE\fR
Change scale of user avatars.
.TP
\fB\-\-camera\-mode MODE\fR
Camera mode (overview,track).
.TP
\fB\-\-disable\-auto\-rotate\fR
Disable automatic camera rotation.
.TP
\fB\-\-disable\-input\fR
Disable keyboard and mouse input.
.TP
\fB\-\-hide DISPLAY_ELEMENT\fR
Hide one or more display elements from the list below:

    bloom     \- bloom effect
    date      \- current date
    dirnames  \- names of directories
    files     \- file icons
    filenames \- names of files
    mouse     \- mouse cursor
    progress  \- progress bar widget
    root      \- root directory of the tree
    tree      \- animated tree structure
    users     \- user avatars
    usernames \- names of users

Separate multiple elements with commas (eg "mouse,progress")

.TP
\fB\-\-hash\-seed SEED\fR
Change the seed of hash function.
.TP
\fB\-\-caption-file FILE
Caption file (see Caption Log Format).
.TP
\fB\-\-caption-size SIZE
Caption size.
.TP
\fB\-\-caption-colour FFFFFF
Caption colour in hex.
.TP
\fB\-\-caption-duration SECONDS
Caption duration.
.TP
\fB\-\-caption-offset X
Caption horizontal offset (0 to centre captions).
.TP
\fB\-o, \-\-output\-ppm\-stream FILE\fR
Output a PPM image stream to a file ('\-' for STDOUT).

This will automatically hide the progress bar initially and enable 'stop\-at\-end' unless other behaviour is specified.

.TP
\fB\-r, \-\-output\-framerate FPS\fR
Framerate of output (25,30,60). Used with \-\-output\-ppm\-stream.
.TP
\fB\-\-output\-custom\-log FILE\fR
Output a custom format log file ('\-' for STDOUT).
.TP
\fB\-\-load\-config CONFIG_FILE\fR
Load a config file.
.TP
\fB\-\-save\-config CONFIG_FILE\fR
Save a config file with the current options.
.TP
\fB\-\-path PATH\fR
.TP
\fBpath\fR
Either a supported version control directory, a pre-generated log file (see log commands or the custom log format), a Gource conf file or '-' to read STDIN.

If path is omitted, gource will attempt to read a log from the current directory.

.SS Git, Bazaar, Mercurial and SVN Examples

View the log of the repository in the current path:

.ti 10
\fIgource\fR

View the log of a project in the specified directory:

.ti 10
\fIgource\fR my\-project\-dir

For large projects, generating a log of the project history may take a long time. For centralized VCS like SVN, generating the log will put load on the central VCS server.

In these cases, you may like to save a copy of the log for later use.

You can generate a log in the VCS specific log format using the \-\-log\-command VCS option:

.ti 10
cd my\-svn\-project
.ti 10
\`\fIgource\fR \-\-log\-command svn\` > my\-svn\-project.log
.ti 10
\fIgource\fR my\-svn\-project.log

You can also have Gource write a copy of the log file in its own format:

.ti 10
\fIgource\fR \-\-output\-custom\-log my\-project\-custom.log

.SS CVS Support

Use 'cvs2cl' to generate the log and then pass it to Gource:

.ti 10
cvs2cl \-\-chrono \-\-stdout \-\-xml \-g\-q > my\-cvs\-project.log
.ti 10
gource my\-cvs\-project.log

.SS Custom Log Format

If you want to use Gource with something other than the supported systems, there is a pipe ('|') delimited custom log format:

.ti 10
timestamp - A unix timestamp of when the update occurred.
.ti 10
username  - The name of the user who made the update.
.ti 10
type      - Single character for the update type - (A)dded, (M)odified or (D)eleted.
.ti 10
file      - Path of the file updated.
.ti 10
colour    - A colour for the file in hex (FFFFFF) format. Optional.

.SS Caption Log Format

Gource can display captions along the timeline by specifying a caption file (using \-\-caption\-file) in the pipe ('|') delimited format below:

.ti 10
timestamp - A unix timestamp of when to display the caption.
.ti 10
caption   - The caption

.SS Recording Videos

See the guide on the homepage for examples of recording videos with Gource:

.ti 10
https://github.com/acaudwell/Gource/wiki/Videos

.SS More Information

Visit the Gource homepage for guides and examples of using Gource with various version control systems:

.ti 10
http://gource.io

.SH INTERFACE
The time shown in the top left of the screen is set initially from the first log entry read and is incremented according to the simulation speed (\-\-seconds\-per\-day).

Pressing SPACE at any time will pause/resume the simulation. While paused you may use the mouse to inspect the detail of individual files and users.

TAB cycles through selecting the current visible users.

The camera mode, either tracking activity or showing the entire code tree, can
be toggled using the Middle mouse button.

You can drag the left mouse button to manually control the camera. The right
mouse button rotates the view.

Interactive keyboard commands:
.sp
.ti 10
(V)   Toggle camera mode
.ti 10
(C)   Displays Gource logo
.ti 10
(K)   Toggle file extension key
.ti 10
(M)   Toggle mouse visibility
.ti 10
(N)   Jump forward in time to next log entry
.ti 10
(S)   Randomize colours
.ti 10
(D)   Toggle directory name display mode
.ti 10
(F)   Toggle file name display mode
.ti 10
(U)   Toggle user name display mode
.ti 10
(G)   Toggle display of users
.ti 10
(T)   Toggle display of directory tree edges
.ti 10
(R)   Toggle display of root directory edges
.ti 10
(+-)  Adjust simulation speed
.ti 10
(<>)  Adjust time scale
.ti 10
(TAB) Cycle through visible users
.ti 10
(F12) Screenshot
.ti 10
(Alt+Enter) Fullscreen toggle
.ti 10
(ESC) Quit
.SH AUTHOR
.nf
 Written by Andrew Caudwell

 Project Homepage: http://gource.io
.SH COPYRIGHT
.nf
 Copyright (C) 2009 Andrew Caudwell (acaudwell@gmail.com)

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version
 3 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
.fi
.SH ACKNOWLEDGEMENTS
.nf
 Catalyst IT (catalyst.net.nz)

 For supporting the development of Gource!
.fi
