
name: Build Gource AppImage

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake libsdl2-dev libpcre3-dev libglew-dev \
            libglm-dev libboost-filesystem-dev libfreetype6-dev libpng-dev \
            libjpeg-dev libfftw3-dev libvorbis-dev libopenal-dev libxrandr-dev \
            libxi-dev libsdl2-* libfuse-dev

      - name: Build Gource
        run: |
          ./autogen.sh
          ./configure
          make

      - name: Download linuxdeploy
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

      - name: Bundle dependencies with linuxdeploy
        run: |
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --executable AppDir/usr/bin/gource --desktop-file AppDir/gource.desktop --icon-file AppDir/gource.png --output appimage

      - name: Prepare AppDir
        run: |
          mkdir -p AppDir/usr/bin
          cp gource AppDir/usr/bin/
          mkdir -p AppDir/usr/share/gource
          cp -r data/* AppDir/usr/share/gource/
          echo "[Desktop Entry]
          Name=Gource
          Exec=gource
          Icon=gource
          Type=Application
          Categories=Graphics;Development;
          Comment=Software version control visualization tool" > AppDir/gource.desktop
          cp data/file.png AppDir/gource.png

      - name: Create AppImage
        run: |
          ./appimagetool-x86_64.AppImage AppDir

      - name: Upload AppImage as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: Gource.AppImage
          path: Gource-x86_64.AppImage
